services:
  api:
    build: .
    container_name: marketplace_by_procrastination
    ports:
      - "${B2B_PORT:-8080}:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - marketplace_db
    networks:
      - shared-network

  marketplace_db:
    image: postgres:16
    container_name: marketplace_db
    ports:
      - "5433:5432"
    volumes:
      - marketplace_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    networks:
      - shared-network


volumes:
  marketplace_postgres_data:

networks:
  shared-network:
    external: true